### ISSUE TITLE
Can't get the value of imgSrc property

### ISSUE THREAD

**Issue by andrebrz** [jwelker110/file-input-accessor#14]
My code is the following:

`<form>
    <input type="file" multiple [formControl]="fileControl" [allowedTypes]="['jpg']" [size]="10" [withMeta]="true">
</form>`

The problem I'm facing is that inside the method 'uploadFiles(files: ICustomFile[])' I cant get the value of the property 'imgSrc'. And it's a bit weird because if I set a console.log to print the File object it prints the imgSrc value, but if I try to access only the property imgSrc it prints undefined. For example:

`  private uploadFiles(files: ICustomFile[]): Observable<Object> {
    if (!files || files.length === 0) {
      console.log('vazio');
      return EMPTY;
    }
    const data = new FormData();

    for (const file of files) {
      console.log(file);
      console.log(file.imgSrc);
      data.append('file', file.slice(), file.name);
    }
    return this._http.post('/api/files', data);
  }
`

OUTPUT:
![image](https://user-images.githubusercontent.com/21268658/89912803-5ccbf000-dbc9-11ea-9e97-52bb631be4a9.png)

My intention is to show the img uploaded in HTML. How could I do this?

**Comment by jwelker110** [comment]
Thank you for taking the time to reach out regarding some unexpected behavior you're seeing.

The reason that the `imgSrc` property is logging `undefined` when you log the property by itself, and contains a value when you log the file object, is because of the way the `imgSrc` value is assigned.

The images are loaded asynchronously and the `imgSrc` property is assigned once the image for a file is loaded. I wrote this this way in order to prevent delays in the form control emitting when files are selected. _Please also take note, that if a file is too large, it will not be able to be converted into a data URL, which means imgSrc will not be assigned a value._

The way that the [demo](https://jwelker110.github.io/file-input-accessor/) displays the images is with the following HTML:

```
<ng-container *ngFor="let file of files">
    <img *ngIf="file.imgSrc" [src]="file.imgSrc" />
</ng-container>
```
Change detection is triggered when the `imgSrc` property is assigned a value, and then the `*ngIf` is evaluated as true and the img element is added to the page.

If you need to wait until **all** the `imgSrc` properties are loaded for the files before you try to access them, try something like the following:

```
this.fileControl.valueChanges.pipe(
    flatMap((values: ICustomFile[]) => {

        // we store the ReplaySubject for each image load in this list
        const imgLoadReplays: Observable<ICustomFile>[] = [];

        for (const file of values) {
            // since we want to access the ICustomFile object AFTER the imgSrc is populated,
            // we need to map each image load emission to the file it belongs to
            imgLoadReplays.push(file.imgLoadReplay.pipe(map(() => file)));
        }

        // forkJoin will wait until every Observable in the list passed to it
        // has completed before it will emit the values as a list
        return forkJoin(imgLoadReplays);

    })
).subscribe((val: ICustomFile[]) => {

    // when we have the values here, the images have been loaded and we can access the
    // imgSrc property
    if (val && val.length > 0) {
        for (const file of val) {
            console.log(file);
            console.log(file.imgSrc);  // this will log the imgSrc now
        }
    }

});
```

I hope this helps. Please let me know if you have any other questions or concerns. Thanks again for taking the time to present your issue.
